// packages/svelte/src/QrCodeGenerator.svelte
<script module lang="ts">
    import type { QrCodeGeneratorCore, ScanUploadFileOrigin, UploadedFile } from '@scanupload/qr-code-generator-core';

    export interface QrCodeGeneratorProps {
        sessionUrl: string;
        /**
         * Optional client identifier (tenant / app GUID). Forwarded to the
         * session-create endpoint as `X-Client-Id` so the hub can scope
         * audit, rate-limits, and per-client rules.
         */
        clientId?: string;
        showHeader?: boolean;
        header?: string;
        showLogo?: boolean;
        clickQrCodeToReload?: boolean;
        filePreviewMode?: 'list' | 'grid';
        size?: 'small' | 'medium' | 'large' | 'xlarge';
        /** Automatically replace an expired session. Default: false. */
        autoResession?: boolean;
        /**
         * Show a "Download all files" button beneath the file previews. When
         * clicked, it fetches every `UploadedFile.url` the SignalR hub has
         * surfaced and triggers a browser save for each. Default: false.
         */
        showDownloadButton?: boolean;
        /**
         * Render the list of files received from the phone inside the widget.
         *
         * Set to `false` when something else already renders them — most commonly
         * an Uppy Dashboard fed by `@scanupload/qr-code-generator-uppy` — so the
         * same files are not shown twice. `filePreviewMode` and
         * `showDownloadButton` are independent of this. Default: `true`.
         */
        showFilePreviews?: boolean;
        /**
         * Bind to an existing core instead of creating one, so this widget shares
         * a single ScanUpload session with whatever already owns that core — most
         * commonly the core exposed by the ScanUpload Uppy plugin.
         *
         * The injected core is configured and disposed by its owner, so
         * `sessionUrl`, `clientId` and `autoResession` are ignored while it is set.
         */
        core?: QrCodeGeneratorCore | null;
        /**
         * Called for every file the hub is holding for this session — including
         * files that were already there when this client connected.
         *
         * Useful for routing files somewhere other than this widget: an uploader,
         * an application-owned list, or analytics. Pair it with `showFilePreviews`
         * set to `false` to render them elsewhere. `origin` is `'restored'` when
         * the file was found during a reconnect resync rather than pushed live.
         */
        onFileAvailable?: (file: UploadedFile, origin: ScanUploadFileOrigin) => void;
        /** Called when the hub drops a single file. Not called for a full clear. */
        onFileRemoved?: (file: UploadedFile) => void;
        /** Called when every file is cleared at once: a session reset, or the session ending. */
        onFilesCleared?: (files: readonly UploadedFile[]) => void;
    }
</script>

<script lang="ts">
    import { createQrCodeController } from './useQrCodeCore';
    import { generateQrSvg } from './qrcode';
    import { REDO_SVG } from './icons';
    import Logo from './components/Logo.svelte';
    import DocumentPreviewer from './components/DocumentPreviewer.svelte';
    import FileList from './components/FileList.svelte';
    import DownloadButton from './DownloadButton.svelte';

    let {
        sessionUrl,
        clientId,
        showHeader = false,
        header = '',
        showLogo = true,
        clickQrCodeToReload = false,
        filePreviewMode = 'grid',
        size = 'large',
        autoResession = false,
        showDownloadButton = false,
        showFilePreviews = true,
        core = null,
        onFileAvailable,
        onFileRemoved,
        onFilesCleared
    }: QrCodeGeneratorProps = $props();

    // The controller is intentionally constructed once with the initial
    // `sessionUrl` / `clientId`. The `$effect` below pushes runtime prop
    // changes into the controller via `setOptions`, so subsequent changes
    // to these props take effect — see `QrCodeCoreController.setOptions`.
    // svelte-ignore state_referenced_locally
    const controller = createQrCodeController({
        sessionUrl,
        clientId,
        autoResession,
        core,
        // Deferred through a closure so a parent that swaps a handler later is
        // still routed to the live one.
        onFileAvailable: (file, origin) => onFileAvailable?.(file, origin),
        onFileRemoved: (file) => onFileRemoved?.(file),
        onFilesCleared: (files) => onFilesCleared?.(files)
    });
    const coreState = controller.state;

    // Push runtime endpoint changes into the core, mirroring the React/Vue adapters.
    $effect(() => {
        void controller.setOptions({ sessionUrl, clientId });
    });

    // Regenerate the QR SVG whenever the device login URL changes.
    let qrSvg = $state('');
    $effect(() => {
        const url = $coreState.deviceLoginUrl || 'http://localhost';
        generateQrSvg(url, 200).then((svg) => (qrSvg = svg));
    });

    const onQrClick = () => {
        if (clickQrCodeToReload) {
            void controller.retrySession();
        }
    };
</script>

<section class="sqg-root" data-size={size}>
    {#if $coreState.loading}
        <div class="sqg-overlay">
            <div class="sqg-loading-content">
                <div class="sqg-spinner"></div>
                <p class="sqg-loading-text">Loading...</p>
            </div>
        </div>
    {/if}
    {#if !$coreState.loading && $coreState.retry}
        <div class="sqg-overlay">
            <div class="sqg-error-content">
                <p class="sqg-error-text">Cannot create session</p>
                <button class="sqg-retry-btn" onclick={() => controller.retrySession()}>{@html REDO_SVG}</button>
            </div>
        </div>
    {/if}
    <div class="sqg-content">
        {#if showHeader}
            <header class="sqg-header">
                <h1 class="sqg-header-title">{header}</h1>
            </header>
        {/if}
        <div
            aria-label="QR Code for file upload"
            class="sqg-qr-wrapper"
            style={clickQrCodeToReload ? 'cursor: pointer' : undefined}
            onclick={onQrClick}
            role="button"
            tabindex="0"
            onkeydown={(e) => {
                if (clickQrCodeToReload && (e.key === 'Enter' || e.key === ' ')) {
                    e.preventDefault();
                    void controller.retrySession();
                }
            }}
        >
            <div class="sqg-qr-inner">
                <div class="sqg-qr-svg">{@html qrSvg}</div>
                {#if showLogo}
                    <div class="sqg-logo-overlay">
                        <Logo isConnected={$coreState.isConnected} />
                    </div>
                {/if}
            </div>
            <p class="sqg-sr-only">QR Code that allows uploads from {$coreState.deviceLoginUrl}</p>
        </div>
        {#if !clickQrCodeToReload}
            <div class="sqg-reload-section">
                <button class="sqg-reload-btn" onclick={() => controller.retrySession()}>
                    {@html REDO_SVG} <span>Reload</span>
                </button>
            </div>
        {:else}
            <div class="sqg-reload-section">
                <p class="sqg-hint-text">Click QR code to reload</p>
            </div>
        {/if}
        {#if showFilePreviews}
            <div class="sqg-file-container">
                {#if filePreviewMode === 'grid'}
                    {#each $coreState.uploadedFiles as file (file.id)}
                        <DocumentPreviewer {file} />
                    {/each}
                {:else}
                    <FileList files={$coreState.uploadedFiles} />
                {/if}
            </div>
        {/if}
        {#if showDownloadButton}
            <DownloadButton core={controller.core} />
        {/if}
    </div>
</section>

// packages/angular/src/qr-code-generator.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    effect,
    Injector,
    Input,
    OnChanges,
    OnDestroy,
    OnInit,
    signal,
    SimpleChanges
} from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import type { QrCodeGeneratorCore, ScanUploadFileOrigin, UploadedFile } from '@scanupload/qr-code-generator-core';
import { LogoComponent } from './components/logo.component';
import { DocumentPreviewerComponent } from './components/document-previewer.component';
import { FileListComponent } from './components/file-list.component';
import { DownloadButtonComponent } from './components/download-button.component';
import { useQrCodeCore, type QrCodeCoreController } from './use-qr-code-core';
import { generateQrSvg } from './qrcode';
import { REDO_SVG } from './icons';

export type FilePreviewMode = 'list' | 'grid';
export type QrCodeSize = 'small' | 'medium' | 'large' | 'xlarge';

@Component({
    selector: 'sqg-qr-code-generator',
    standalone: true,
    imports: [LogoComponent, DocumentPreviewerComponent, FileListComponent, DownloadButtonComponent],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <section class="sqg-root" [attr.data-size]="size">
            @if (controller && controller.state().loading) {
                <div class="sqg-overlay">
                    <div class="sqg-loading-content">
                        <div class="sqg-spinner"></div>
                        <p class="sqg-loading-text">Loading...</p>
                    </div>
                </div>
            }
            @if (controller && !controller.state().loading && controller.state().retry) {
                <div class="sqg-overlay">
                    <div class="sqg-error-content">
                        <p class="sqg-error-text">Cannot create session</p>
                        <button class="sqg-retry-btn" [innerHTML]="redoIcon" (click)="retry()"></button>
                    </div>
                </div>
            }
            <div class="sqg-content">
                @if (showHeader) {
                    <header class="sqg-header">
                        <h1 class="sqg-header-title">{{ header }}</h1>
                    </header>
                }
                <div
                    aria-label="QR Code for file upload"
                    class="sqg-qr-wrapper"
                    [style.cursor]="clickQrCodeToReload ? 'pointer' : null"
                    (click)="onQrClick()"
                >
                    <div class="sqg-qr-inner">
                        <div class="sqg-qr-svg" [innerHTML]="qrSvg()"></div>
                        @if (showLogo) {
                            <div class="sqg-logo-overlay">
                                <sqg-logo [isConnected]="controller?.state()?.isConnected ?? false"></sqg-logo>
                            </div>
                        }
                    </div>
                    <p class="sqg-sr-only">QR Code that allows uploads from {{ controller?.state()?.deviceLoginUrl }}</p>
                </div>
                @if (!clickQrCodeToReload) {
                    <div class="sqg-reload-section">
                        <button class="sqg-reload-btn" (click)="retry()"><span [innerHTML]="redoIcon"></span> <span>Reload</span></button>
                    </div>
                } @else {
                    <div class="sqg-reload-section">
                        <p class="sqg-hint-text">Click QR code to reload</p>
                    </div>
                }
                @if (showFilePreviews) {
                    <div class="sqg-file-container">
                        @if (filePreviewMode === 'grid') {
                            @for (file of controller?.state()?.uploadedFiles ?? []; track file.id) {
                                <sqg-document-previewer [file]="file"></sqg-document-previewer>
                            }
                        } @else {
                            <sqg-file-list [files]="controller?.state()?.uploadedFiles ?? []"></sqg-file-list>
                        }
                    </div>
                }
                @if (showDownloadButton) {
                    <sqg-download-button [core]="controller?.core"></sqg-download-button>
                }
            </div>
        </section>
    `
})
export class QrCodeGeneratorComponent implements OnInit, OnChanges, OnDestroy {
    @Input({ required: true }) sessionUrl!: string;
    @Input() clientId?: string;
    @Input() showHeader = false;
    @Input() header = '';
    @Input() showLogo = true;
    @Input() clickQrCodeToReload = false;
    @Input() filePreviewMode: FilePreviewMode = 'grid';
    @Input() size: QrCodeSize = 'large';
    /** Automatically replace an expired session. Default: false. */
    @Input() autoResession = false;
    @Input() showDownloadButton = false;
    /**
     * Render the list of files received from the phone inside the widget.
     *
     * Set to `false` when something else already renders them — most commonly an
     * Uppy Dashboard fed by `@scanupload/qr-code-generator-uppy` — so the same
     * files are not shown twice. `filePreviewMode` and `showDownloadButton` are
     * independent of this. Default: `true`.
     */
    @Input() showFilePreviews = true;
    /**
     * Bind to an existing core instead of creating one, so this widget shares a
     * single ScanUpload session with whatever already owns that core — most
     * commonly the core exposed by the ScanUpload Uppy plugin.
     *
     * The injected core is configured and disposed by its owner, so
     * `sessionUrl`, `clientId` and `autoResession` are ignored while it is set.
     */
    @Input() core?: QrCodeGeneratorCore | null;
    /**
     * Called for every file the hub is holding for this session — including
     * files that were already there when this client connected.
     *
     * Useful for routing files somewhere other than this widget: an uploader, an
     * application-owned list, or analytics. Pair it with `showFilePreviews` set
     * to `false` to render them elsewhere. `origin` is `'restored'` when the file
     * was found during a reconnect resync rather than pushed live.
     */
    @Input() onFileAvailable?: (file: UploadedFile, origin: ScanUploadFileOrigin) => void;
    /** Called when the hub drops a single file. Not called for a full clear. */
    @Input() onFileRemoved?: (file: UploadedFile) => void;
    /** Called when every file is cleared at once: a session reset, or the session ending. */
    @Input() onFilesCleared?: (files: readonly UploadedFile[]) => void;

    protected controller?: QrCodeCoreController;
    protected readonly qrSvg = signal<SafeHtml>('');
    protected readonly redoIcon: SafeHtml;

    constructor(
        private readonly sanitizer: DomSanitizer,
        private readonly injector: Injector
    ) {
        this.redoIcon = sanitizer.bypassSecurityTrustHtml(REDO_SVG);
    }

    ngOnInit(): void {
        this.controller = useQrCodeCore({
            sessionUrl: this.sessionUrl,
            clientId: this.clientId,
            autoResession: this.autoResession,
            core: this.core,
            // Routed through `this` so an input bound after `ngOnInit` still
            // reaches the live handler.
            onFileAvailable: (file, origin) => this.onFileAvailable?.(file, origin),
            onFileRemoved: (file) => this.onFileRemoved?.(file),
            onFilesCleared: (files) => this.onFilesCleared?.(files)
        });
        this.controller.start();

        // Regenerate the QR SVG whenever the device login URL changes.
        effect(
            () => {
                const url = this.controller?.state().deviceLoginUrl || 'http://localhost';
                generateQrSvg(url, 200)
                    .then((svg) => this.qrSvg.set(this.sanitizer.bypassSecurityTrustHtml(svg)))
                    .catch(() => undefined);
            },
            { injector: this.injector }
        );
    }

    ngOnChanges(changes: SimpleChanges): void {
        if (this.controller && (changes['sessionUrl'] || changes['clientId'])) {
            void this.controller.setOptions({
                sessionUrl: this.sessionUrl,
                clientId: this.clientId
            });
        }
    }

    ngOnDestroy(): void {
        this.controller?.dispose();
    }

    protected retry(): void {
        void this.controller?.retrySession();
    }

    protected onQrClick(): void {
        if (this.clickQrCodeToReload) {
            void this.controller?.retrySession();
        }
    }
}
