// packages/react/src/components/ProgressBar.tsx
import React from "react";

interface ProgressBarProps {
  progress: number;
}

const ProgressBar: React.FC<ProgressBarProps> = ({ progress = 0 }) => (
  <div className="sqg-progress-wrap">
    <div className="sqg-progress-labels">
      <span className="sqg-progress-label">Uploading...</span>
      <span className="sqg-progress-label">{Math.round(progress || 0)}%</span>
    </div>
    <div className="sqg-progress-track">
      <div
        className="sqg-progress-fill"
        style={{ width: `${progress || 0}%` }}
      />
    </div>
  </div>
);

export default ProgressBar;

// packages/vue/src/components/ProgressBar.vue
<script setup lang="ts">
withDefaults(
    defineProps<{
        progress?: number;
    }>(),
    {
        progress: 0
    }
);
</script>

<template>
    <div class="sqg-progress-wrap">
        <div class="sqg-progress-labels">
            <span class="sqg-progress-label">Uploading...</span>
            <span class="sqg-progress-label">{{ Math.round(progress || 0) }}%</span>
        </div>
        <div class="sqg-progress-track">
            <div class="sqg-progress-fill" :style="{ width: `${progress || 0}%` }" />
        </div>
    </div>
</template>
